### ISSUE TITLE
Can't editing an existing Location

### ISSUE THREAD

**Issue by flapanther33781** [davidjeddy/yii2-resutoran#14]
When I go to the Locations tab and click Edit I'm taken to the first page of that location's data and can update that, but the Update button takes me back to the main Locations tab.  It needs to take me to the next page worth of data for that location so I can edit all of it.

**Comment by davidjeddy** [comment]
This should not be fixed as of the 0.0.28 release on 2017-05-28 @ 20:15. Please verify and close if corrected.

**Comment by flapanther33781** [comment]
PHP Parse Error – yii\base\ErrorException
syntax error, unexpected '?'

    1. in /usr/share/nginx/html/vendor/davidjeddy/yii2-resutoran/src/backend/controllers/ResuLocationNewProcessController.php at line 77
    68697071727374757677787980818283848586

         */
        public function actionAddAdditionalOption($id)
        {
            $model = \resutoran\common\models\ResuLocation::findOne($id);
     
            if (Yii::$app->request->isPost === true) {
     
                $saveStatus  = $this->saveResuLocDressOption(
                    $id,
                    (\Yii::$app->request->post()['ResuLocation']['location_options']['resu_location_dress_code'] ?? null)
                );
     
                $saveStatus2 = $this->saveBooleanOptionValues(
                    $id,
                    (\Yii::$app->request->post()['ResuLocation']['resu_location_boolean'] ?? null)
                );
     
                if ($saveStatus === true && $saveStatus2 === true) {
                    return \Yii::$app->response->redirect('add-contact?id=' . $id);

    2. yii\base\ErrorHandler::handleFatalError()

$_COOKIE = [
    '_identity' => '502a0e17269064593929f4c31a9e084077eb209698bfc7e408402ba227bf17efa:2:{i:0;s:9:"_identity";i:1;s:46:"[2,"nDmtFSC7tk020z0NNUmJ92OMO5obC6NL",2592000]";}',
    'PHPSESSID' => '247kkgimsd9mo93qi7ii6eifu7',
    '_csrf' => '26a48163cfa42f3eb0860524ef2ff7c65a38f075f8f2ec4038ff05b3c6bf7947a:2:{i:0;s:5:"_csrf";i:1;s:32:"X7V38YaXvxGLWOrEfFtlDqX7hfa5OtSO";}',
];

$_SESSION = [
    '__flash' => [],
    '__id' => 2,
];

**Comment by davidjeddy** [comment]
Corrected, Upgraded server to ubuntu 16 w/ PHP 7.1. Better matches development ENV now as well.

**Comment by flapanther33781** [comment]
I got past the first page, selected a few things that weren't selected previously, hit Next and got an error:

https://zeroforksgiven.com/admin/resutoran/resu-location-new-process/add-additional-option?id=1

**Comment by flapanther33781** [comment]
Locations are now editable. Closing ticket.
