### ISSUE TITLE
Check AWS security settings

### ISSUE THREAD

**Issue by flapanther33781** [davidjeddy/yii2-resutoran#18]
I just read this article:

https://rhinosecuritylabs.com/penetration-testing/penetration-testing-aws-storage/

wherein a security researcher pentested the 10,000 largest websites and found 1% of them having an opening described in the article.  Please check ZFG for this potential security hole.

**Comment by davidjeddy** [comment]
We do not currently use the AWS S3 service.

Good read though. +1
