### ISSUE TITLE
Iterated on location creation -> hours step

### ISSUE THREAD

**Issue by davidjeddy** [davidjeddy/yii2-resutoran#5]
Allow all days of week to be submitted at the same time

**Comment by davidjeddy** [comment]
Try using the new location creation process: https://zeroforksgiven.com/admin/resutoran/resu-location-new-process/create

**Comment by flapanther33781** [comment]
I think this style of inputting hours is a different from what we had previously but it isn't a showstopper.  It works for now and we can make a change request later.
